### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by KEINOS** [yoshi389111/git-caesar#2]
Awesome app! 👍 

I would also like to be able to install `git-caesar` from Homebrew, a package manager for macOS and Linux. Such like so:

```bash
$ brew install yoshi389111/apps/git-caesar
```

I would like to PR for this but what do you think?

**Comment by KEINOS** [comment]
> Of course, pull requests are welcome.

Cool.

To support Homebrew we need a brand new repository with a `homebrew-` prefix to place the `brew` packages.

Please create a blank repo at `github.com/yoshi389111/homebrew-apps` or `github.com/yoshi389111/homebrew-git-caesar` when you got time.

I recommend `github.com/yoshi389111/homebrew-apps` for your future app.

**Comment by yoshi389111** [comment]
I got it.

I created an empty repository.

https://github.com/yoshi389111/homebrew-apps
